### ISSUE TITLE
Feature request: dot files instead of PNGs

### ISSUE THREAD

**Issue by sei-cabidi** [IBM/NOVIA#5]
Hello there! Would it be possible to integrate the generation of .dot files alongside the .pngs generated by NOVIA?

It would be useful on our end since some of our software analysis utilities ingest .dot files.

**Comment by dtrilla** [comment]
Hello!

It is indeed possible and will take that into account for the next release which should come soon. I will probably add some option to activate that.

In the meantime, you can modify lines 162 and 356 of BBVisualization.cpp:

`gvRenderFilename(gvc,G,"png",string(dir+"/"+string(file)+".png").c_str());`

and change it to instead output dot files by changing the format string in the third argument ( you might probably want to change the filename suffix too)

`  gvRenderFilename(gvc,G,"dot",string(dir+"/"+string(file)+".dot").c_str());`


I'll leave the issue open until the next push properly adds this feature.

**Comment by dtrilla** [comment]
Added novia.conf with NOVIA_VIZ_FORMAT switching png or dot formats. In branch novia-1.5.0
